#!/usr/bin/env bash

set -eo pipefail

SCRIPT_PATH="$( cd "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

DOCKER_IMAGE="ottoapi/docs-server"
DOCKER_IMAGE_VERSION="latest"
DOCKER_FILE="$SCRIPT_PATH/Dockerfile"
DOCKER_BUILD_CONTEXT="$SCRIPT_PATH/../../"

DOCS_SERVER_PORT="${DOCS_SERVER_PORT:-3000}"
DOCS_SERVER_CONTAINER_NAME="ottoapi-docs-server"

docker build \
    --rm \
    -t $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION \
    --build-arg GITHUB_TOKEN=$GITHUB_TOKEN \
    -f $DOCKER_FILE \
    $DOCKER_BUILD_CONTEXT

docker run \
    --rm \
    -p $DOCS_SERVER_PORT:3000 \
    --name $DOCS_SERVER_CONTAINER_NAME \
    -v $DOCKER_BUILD_CONTEXT/guidelines:/opt/app/guidelines \
    -it $DOCKER_IMAGE:$DOCKER_IMAGE_VERSION
