name: Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit-ref:
        description: Revision number of commit

jobs:
  changelog:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      packages: read
      pull-requests: read

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm ci

      - name: Git configuration
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Changelog Entry
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          COMMIT_REF: ${{github.event.inputs.commit-ref}}
        run: |
          npm run changelog

      - name: Auto commit
        if: success()
        uses: stefanzweifel/git-auto-commit-action@v4.16.0
        with:
          commit_message: "chore(changelog): update changelog"
          file_pattern: "changes/changelog.md"
